version: "2"

services:
  vote:
    build: ./vote
    command: python app.py
    ports:
      - "50000:80"
    environment:
      #REDIS_HOST: "votes.redis.cache.windows.net"
      #REDIS_KEY: "I+7ZwyYT5q8Kk6DsoKUAgs+asKyIo0/SJDbW2Rs8E/g="
      REDIS_HOST: "redis"
      REDIS_KEY: "redis"
    networks:
      - front-tier
      - back-tier

  result:
    build: ./result
    command: nodemon --debug server.js
    ports:
      - "50001:80"
      - "5858:5858"
    environment:
      DB_HOST: "db"
      DB_USER: "sa"
      DB_PASSWORD: "sa"
      DB_NAME: "Votes"
    networks:
      - front-tier
      - back-tier

  worker:
    build: ./worker
    environment:
      DB_HOST: "db"
      DB_USER: "sa"
      DB_PASSWORD: "sa"
      DB_NAME: "Votes"
      #REDIS_HOST: "votes.redis.cache.windows.net"
      #REDIS_KEY: "I+7ZwyYT5q8Kk6DsoKUAgs+asKyIo0/SJDbW2Rs8E/g="
      REDIS_HOST: "redis"
      REDIS_KEY: "redis"
    networks:
      - back-tier

  redis:
    image: redis:alpine
    command: redis-server --requirepass redis
    container_name: redis
    ports: ["6379"]
    networks:
      - back-tier

  db:
    image: private-repo.microsoft.com/mssql-private-preview/mssql-server
    container_name: db
    volumes:
      - "db-data:/var/opt/mssql/data"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "sa"
      ACCEPT_EULA: "Y"
    networks:
      - back-tier

volumes:
  db-data:
    driver: azurefile
    driver_opts:
      share: "votes"

networks:
  front-tier:
  back-tier: